version: "3.8"

services:
  flask_app:
    build: .
    container_name: "img_to_ascii"
    ports:
      - "5000:5000"
    volumes:
      - /images_ascii_db:/app/static
    environment:
      - FLASK_ENV=development
    networks:
      - ascii_custom_net  

networks:
  ascii_custom_net:
    name: ascii_image_network
    driver: bridge  
