version: "3.8"

services:
  flask_app:
    build: .
    container_name: "img_to_ascii"
    ports:
      - "5000:5000"
    volumes:
      - ./uploaded_images:/app/static
    environment:
      - FLASK_ENV=development
